# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mascota', models.IntegerField()),
                ('razones', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona'),
        ),
    ]
